### ISSUE TITLE
sha256 mismatch error?

### ISSUE THREAD

**Issue by nimasghari** [PippoRJ/hugo-refresh#29] opened 2020-04-17 10:27 UTC
Hey, thanks for making a cool theme.

When I install and run hugo server -D, everything works.
But when I run hugo -D and move the public files to my server I get this error message in the console and the resources don't load:
- None of the “sha256” hashes in the integrity attribute match the content of the subresource.

Also when building I get this message:
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

I wonder if there's something wrong with the files or it's my set up. I've set up a few other themes successfully and followed instructions carefully.

Thanks very much!
-Nima

**Comment by PippoRJ** [comment] 2020-04-17 11:01
Hey @nimasghari 
don't worry about the warning, I am testing the presence of some configuration options and if not present they issue a warning. I will fix it sometime in the future.

The sha256 error message it is strange. 
Can you edit a single html page (from your server) and remove the "integrity" property from all the script elements, then reload the page. Is the error still there? 

It is very strange that it works fine with `hugo server -D` but doesn't work if you copy the files to your server.

**Comment by nimasghari** [comment] 2020-04-17 19:06
Thanks @PippoRJ 

When I remove integrity property from all the script elements I no longer get the error and the page fully loads.

I can try a few more times later, and start with a fresh install - though I did try 3 times yesterday.

**Comment by PippoRJ** [comment] 2020-04-17 19:44
Good.. I will make same tests hoping to be able to reproduce it.

**Comment by PippoRJ** [comment] 2020-05-24 12:00
Hi @nimasghari , sorry but I can't reproduce the error, I am going to close the issue.

**Closed by PippoRJ** 2020-05-24 12:00 UTC
